# This is an example neoforge.mods.toml file. It contains the data relating to the loading of mods.
# There are several mandatory fields:
# - modLoader: The language loader this mod uses (javafml or kotlinforforge)
# - loaderVersion: The version range of the mod loader that this mod is compatible with
# - license: The license for this mod
# The rest are optional fields that you can add if you want.

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/createcannons/createcannons/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"
displayURL="https://github.com/createcannons/createcannons"
logoFile="createcannons_logo.png"

# Dependencies
# NeoForge dependency
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Minecraft dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Create dependency
[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[0.5.1,)"
ordering="AFTER"
side="BOTH"

# Features are used to specify version specific features your mod requires
# Define optional features for client-only stuff
[[mixins]]
config="${mod_id}.mixins.json"

# Access transformers
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
